python/voting_app/config/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'', include('users.urls', namespace='user')),
    url(r'^polls/', include('polls.urls', namespace='polls')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'^admin997/', admin.site.urls),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
]

python/voting_app/polls/urls.py
from django.conf.urls import url

from polls import views

app_name = 'polls'
urlpatterns = [
    url(r'^vote/(?P<pk>\d+)/$', views.PollVoteView.as_view(), name='user_poll_vote'),
    url(r'^details/(?P<pk>\d+)/$', views.PollDetailsView.as_view(), name='user_poll_details'),
]

python/voting_app/users/urls.py
from django.conf.urls import url

from users import views

app_name = 'users'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^home/$', views.UserHomePage.as_view(), name='home'),

]

python/voting_app/polls/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class Poll(models.Model):
    end_date = models.DateTimeField(null=False)
    title = models.CharField(max_length=1024, null=False)

    def __str__(self):
        return self.title

    def is_actual(self):
        return self.end_date >= timezone.now()


class PollOption(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE, related_name='polloptions')
    name = models.CharField(max_length=512)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.name

    def add_vote(self):
        self.votes += 1


class UserParticipation(models.Model):
    poll = models.ForeignKey(Poll)
    user = models.ForeignKey(User)

python/voting_app/users/models.py
from django.db import models

# Create your models here.

python/voting_app/polls/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.views import View

from polls.form import PollForm
from polls.models import Poll, UserParticipation


@method_decorator(login_required, name='dispatch')
class PollVoteView(View):
    template_name = 'polls/user_poll_vote.html'
    form_class = PollForm

    def get_queryset(self):
        return Poll.objects.prefetch_related('polloptions').get(pk=self.kwargs.get('pk'))

    def dispatch(self, request, *args, **kwargs):
        poll = self.get_queryset()
        if not poll.is_actual():
            return redirect('polls:user_poll_details', pk=(self.kwargs.get('pk')))
        if UserParticipation.objects.filter(user=request.user, poll=poll).exists():
            return render(request, 'polls/user_poll_already_voted.html', {'poll': poll})

        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        poll = self.get_queryset()
        form = PollForm(instance=poll)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = PollForm(request.POST, instance=self.get_queryset())
        if form.is_valid():
            form.save()
            # annotate that user has already participate to this poll
            UserParticipation(user=request.user, poll=self.get_queryset()).save()
            return render(request, 'polls/user_poll_success_vote.html')
        else:
            return render(request, self.template_name, {'form': form})


@method_decorator(login_required, name='dispatch')
class PollDetailsView(View):
    template_name = 'polls/user_poll_details.html'

    def get_queryset(self):
        return Poll.objects.prefetch_related('polloptions').get(pk=self.kwargs.get('pk'))

    def get(self, request, *args, **kwargs):
        poll = self.get_queryset()
        if not request.user.is_superuser and poll.is_actual():
            return redirect('polls:user_poll_vote', pk=(self.kwargs.get('pk')))
        return render(request, self.template_name, {'poll': poll})

python/voting_app/users/views.py
from datetime import datetime

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.views import View
from django_tables2.config import RequestConfig

from polls.models import Poll
from polls.tables import PollsTable


class IndexView(View):
    template_name = 'index.html'

    def get(self, request):
        if request.user.is_authenticated():
            return redirect('users:home')
        return render(request, self.template_name)


class UserHomePage(View):
    template_name = 'users/user_homepage.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self, request):
        actual_polls = PollsTable(Poll.objects.filter(end_date__gte=datetime.now()).all())
        ended_polls = PollsTable(Poll.objects.filter(end_date__lte=datetime.now()).all())
        RequestConfig(request).configure(actual_polls)
        RequestConfig(request).configure(ended_polls)

        return render(request, self.template_name, {'actual_polls': actual_polls,
                                                    'ended_polls': ended_polls})

python/voting_app/polls/templates/polls/user_poll_already_voted.html
{% extends 'base.html' %}

{% block content %}
<h2> Sorry. </h2>
    <p>But you have already voted in "{{ poll.title }}" poll.</p>
{% endblock %}

python/voting_app/polls/templates/polls/user_poll_details.html
{% extends 'base.html' %}

{% block content %}
    <div class="wrapper">
        <h2>Result of poll "{{ poll.title }}": </h2>
        <div id="piechart">
        </div>
        <div id="barchart_values">
        </div>
    </div>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">

// Load google charts
google.charts.load('current', {'packages':['corechart']});
google.charts.setOnLoadCallback(drawPieChart);
google.charts.setOnLoadCallback(drawBarChart);

// Draw the chart and set the chart values
function drawPieChart() {
    var data = google.visualization.arrayToDataTable([
        ['vote', 'number of votes'],
        {% for poll_opiton in poll.polloptions.all %}
            ['{{ poll_opiton.name }}', {{ poll_opiton.votes }}],
        {% endfor %}
    ]);

    // Optional; add a title and set the width and height of the chart
    var options = {'title': '{{ poll.title }}', 'width': 500, 'height': 500, sliceVisibilityThreshold: 0};

    // Display the chart inside the <div> element with id="piechart"
    var chart = new google.visualization.PieChart(document.getElementById('piechart'));
    chart.draw(data, options);
}

function drawBarChart() {
    var data = google.visualization.arrayToDataTable([
         ['vote', 'number of votes'],
          {% for poll_opiton in poll.polloptions.all %}
              ['{{ poll_opiton.name }}', {{ poll_opiton.votes }}, ],
          {% endfor %}

      ]);
    var options = {
        title: "{{ poll.title }}",
        width: 600,
        height: 400,
        sliceVisibilityThreshold:0,
        bar: {groupWidth: "95%"},
        legend: { position: "none" },
      };
      var chart = new google.visualization.BarChart(document.getElementById("barchart_values"));
      chart.draw(data, options);

}
</script>
{% endblock %}

python/voting_app/polls/templates/polls/user_poll_success_vote.html
{% extends 'base.html' %}

{% block content %}
<h2> Success! </h2>
    <p>Your vote have been added.</p>
    <p>Please wait until poll end date to see the results.</p>
{% endblock %}

python/voting_app/polls/templates/polls/user_poll_vote.html
{% extends 'base.html' %}

{% block content %}
    <form action="{% url 'polls:user_poll_vote' pk=form.instance.id %}" method="post">
        {% csrf_token %}
        <h2>{{ form.poll_question }}</h2>
        {{ form.as_p }}
        <input type="submit" value="Submit" />
    </form>

    <p>You can vote until: <b>{{ form.poll_expiration_date }}</b></p>
{% endblock %}

python/voting_app/users/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Polls</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
 <nav class="navbar navbar-light bg-faded bg-inverse" id="nav-header">

  <a class="navbar-brand" href="{% url 'users:index' %}">
    <img alt="Polls" src="{% static 'poll_logo.png' %}">
  </a>
  <h3 id="nav-header-text">Let's vote!</h3>

   {% if user.is_authenticated %}
   <form action="{% url 'logout' %}"><button type="submit" class="btn btn-primary btn-sign-out">Sign out</button></form>
   {% endif %}

</nav>
 <div class="panel-body">
 {% block content %}

 {% endblock %}
 </div>
</body>
</html>

python/voting_app/users/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2>Welcome</h2>
<p>
    This service provides you the ability to vote in prepare polls. Remember your vote maters!
</p>

<p>
   To make vote you must login in using Google+ account. <br />
   <a href="{% url 'social:begin' 'google-oauth2' %}"><img src="{% static 'btn_google_signin_dark_normal_web.png' %}" alt="log in with google+"/>  </a>
</p>

<footer>
    <p>Authors: Michał Dąbrowski, Paweł Drapiewski</p>
</footer>
{% endblock %}

python/voting_app/users/templates/users/user_homepage.html
{% extends 'base.html' %}
{% load render_table from django_tables2 %}

{% block content %}
<head>
    <meta charset="UTF-8">
    <title>User homepage</title>
</head>
<body>
 <h2>Hello, {{ user.username }}!</h2>

 <div class="poll-active polls-list">
     <h3 class="header">Active polls:</h3>
     {% if actual_polls.data %}
       {% render_table actual_polls %}
     {% else %}
        <div class="poll-warring">There is no polls.</div>
     {% endif %}
  </div>


  <div class="poll-ended polls-list">
      <h3 class="header">Polls that ended:</h3>
      {% if ended_polls.data %}
          {% render_table ended_polls %}
      {% else %}
          <div class="poll-warring">There is no polls.</div>
      {% endif %}

 </div>
</body>
{% endblock %}